pipeline {
    agent { label 'linux' }
    stages {
        stage('Build Image') {
            steps {
                sh """
                    docker build -t hello_there -f ./extra/Dockerfile .
                """
            }
        }
        
        stage('Running Image') {
            steps {
                sh """
                    docker run --rm hello_there
                """
            }
        }
    }
}
