---
- hosts: target
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Import jenkins key from url
    shell:
      "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null"

  - name: Step 2
    shell:
      "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null"

  - name: apt update
    apt:
      name: '*'
      state: latest

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started