---
- hosts: main
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Import jenkins key from url
    get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      dest: /usr/share/keyrings/jenkins-keyring.asc 

  - name: Step 2
    shell:
      "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null"
  
  - name: "Update cache & Full system update"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true

  # - name: apt update
  #   apt:
  #     name: '*'
  #     state: latest

  - name: Install java
    apt:
      name: openjdk-11-jre-headless
      state: present

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started